### ISSUE TITLE
Correct day display

### ISSUE THREAD

**Issue by LuissForce** [KUJP-code/materials#46] opened 2024-06-03 06:08 UTC
Stand show and speak time have the same issue, in which it displays the same day for all the dates
![image](https://github.com/KUJP-code/materials/assets/161788348/8ff92769-b162-42fe-b9dc-e7c561cc3209)

**Comment by Brett-Tanner** [comment] 2024-06-03 06:10
Duplicate of #42

**Closed by Brett-Tanner** 2024-06-03 06:10 UTC
